### ISSUE TITLE
AddWorkingHours error

### ISSUE THREAD

**Issue by thuytd86** [paonath/PH.WorkingDaysAndTime#5]
hello
error,  use AddWorkingHours
Code:

            var wts1 = new WorkTimeSpan()
             { Start = new TimeSpan(08, 00, 0), End = new TimeSpan(12, 0, 0) };
             var wts2 = new WorkTimeSpan()
             { Start = new TimeSpan(13, 30, 0), End = new TimeSpan(17, 30, 0) };
             var wts = new List<WorkTimeSpan>() { wts1, wts2 };

             var start = new DateTime(2023, 1, 11, 8, 0, 0);
             var end = new DateTime(2023, 1, 11, 10, 0, 0);
             var italiansHoliDays = new List<AHolyDay>() { new EasterMonday() };
             var week = new WeekDaySpan()
             {
                 WorkDays = new Dictionary<DayOfWeek, WorkDaySpan>()
                 {
                     {DayOfWeek.Monday, new WorkDaySpan() {TimeSpans = wts}}
                     ,
                     {DayOfWeek.Tuesday, new WorkDaySpan() {TimeSpans = wts}}
                     ,
                     {DayOfWeek.Wednesday, new WorkDaySpan() {TimeSpans = wts}}
                     ,
                     {DayOfWeek.Thursday, new WorkDaySpan() {TimeSpans = wts}}
                     ,
                    {DayOfWeek.Friday, new WorkDaySpan() {TimeSpans = wts}}
                     ,
                      {DayOfWeek.Saturday, new WorkDaySpan() {TimeSpans = wts}}
                 }
             };
             var utility = new WorkingDaysAndTimeUtility(week, italiansHoliDays);
             var result = utility.AddWorkingDays(new DateTime(2023, 1, 13), 3);
             var dateTime = new DateTime(2023, 1, 18, 12, 30, 22);
             result = utility.AddWorkingHours(dateTime, 1);

  AddWorkingHours is lost in time
Can you help?

**Comment by paonath** [comment]
You're right,:
```csharp

var dateTime = new DateTime(2023, 1, 18, 12, 30, 22);
result = utility.AddWorkingHours(dateTime, 1);

```
`result` should be 2023-01-18 14:30:22

**Comment by paonath** [comment]
please check v.2.0.12
