### ISSUE TITLE
Help function with staff on half-day leave

### ISSUE THREAD

**Issue by thuytd86** [paonath/PH.WorkingDaysAndTime#9]
Dear author,
I am using your library for working time solution and everything works great.
However, in reality there are some cases of hourly leave,
For example, they apply for leave in the morning at 8:00 am to 12:00 pm on February 14, 2023.
So now how can I calculate working time for employees if they take leave in the morning and that work is calculated from 1:30 to 5:30?.
If possible, please add more libraries to help me,
Thank you very much

**Comment by paonath** [comment]
The goal of WorkingDaysAndTime is calculate num of _working hours_, you have on your domain the number of _worked hours_.
So for employee1 on 14-feb you already kown he worked from 1:30 to 5:30 pm.
